# Generated by Django 5.1.1 on 2024-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bigdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('subhead1', models.CharField(max_length=35)),
                ('subtxt1', models.CharField(max_length=400)),
                ('subhead2', models.CharField(max_length=50)),
                ('subtxt2', models.CharField(max_length=400)),
                ('subhead3', models.CharField(max_length=50)),
                ('subtxt3', models.CharField(max_length=400)),
                ('subhead4', models.CharField(max_length=50)),
                ('subtxt4', models.CharField(max_length=400)),
                ('lowerhead', models.CharField(max_length=30)),
                ('fsubhead1', models.CharField(max_length=25)),
                ('fsubtxt1', models.CharField(max_length=125)),
                ('fsubhead2', models.CharField(max_length=25)),
                ('fsubtxt2', models.CharField(max_length=125)),
                ('fsubhead3', models.CharField(max_length=25)),
                ('fsubtxt3', models.CharField(max_length=125)),
                ('fsubhead4', models.CharField(max_length=25)),
                ('fsubtxt4', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('mesg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=200)),
                ('requiredpictures', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='itesglobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('subhead1', models.CharField(max_length=35)),
                ('subtxt1', models.CharField(max_length=400)),
                ('subhead2', models.CharField(max_length=50)),
                ('subtxt2', models.CharField(max_length=400)),
                ('subhead3', models.CharField(max_length=50)),
                ('subtxt3', models.CharField(max_length=400)),
                ('subhead4', models.CharField(max_length=50)),
                ('subtxt4', models.CharField(max_length=400)),
                ('lowerhead', models.CharField(max_length=30)),
                ('fsubhead1', models.CharField(max_length=25)),
                ('fsubtxt1', models.CharField(max_length=125)),
                ('fsubhead2', models.CharField(max_length=25)),
                ('fsubtxt2', models.CharField(max_length=125)),
                ('fsubhead3', models.CharField(max_length=25)),
                ('fsubtxt3', models.CharField(max_length=125)),
                ('fsubhead4', models.CharField(max_length=25)),
                ('fsubtxt4', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='jobforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phoneno', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resume/')),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='masterdatamanagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('subhead1', models.CharField(max_length=35)),
                ('subtxt1', models.CharField(max_length=400)),
                ('subhead2', models.CharField(max_length=50)),
                ('subtxt2', models.CharField(max_length=400)),
                ('subhead3', models.CharField(max_length=50)),
                ('subtxt3', models.CharField(max_length=400)),
                ('subhead4', models.CharField(max_length=50)),
                ('subtxt4', models.CharField(max_length=400)),
                ('lowerhead', models.CharField(max_length=30)),
                ('fsubhead1', models.CharField(max_length=25)),
                ('fsubtxt1', models.CharField(max_length=125)),
                ('fsubhead2', models.CharField(max_length=25)),
                ('fsubtxt2', models.CharField(max_length=125)),
                ('fsubhead3', models.CharField(max_length=25)),
                ('fsubtxt3', models.CharField(max_length=125)),
                ('fsubhead4', models.CharField(max_length=25)),
                ('fsubtxt4', models.CharField(max_length=125)),
            ],
        ),
    ]
